### ISSUE TITLE
Error / Not available / 404 msg

### ISSUE THREAD

**Issue by jfass** [amschaal/bioshare#18]
Add general notification(s?) to home page or subset of pages to notify users of problems ... 

See today's problem with all the PacBio links. Maybe this is just handled by adding general notifications to the landing page? Maybe the 404 page should have a link back to the landing page so people see any notifications (which might explain 404)? See Matt for questions about this issue ..

**Comment by amschaal** [comment]
The most likely errors to occur are:
1.  The file/folder for a specific path not existing.  I agree that there could be a more useful error message. 
2. A share not existing (no longer exists or bad link).  Another error that should have a more useful message.
3.  The user entered the wrong URL and get a typical 404 page not found error.

Regarding notifications, I have considered this.  I'd consider also using it to notify users of new features.  Do you think having them at the bottom of the bar on the left of the screen would be appropriate?  There could be an animated gif star or dancing baby whenever we thought it particularly important (like a system outage or something). ;)

**Comment by msettles** [comment]
More of a way to provide system wide notifications.  Recently all the pac
bio data wasnt available, instead of getting a bunch of emails on why
someone cant access their data, would be nice to post system wide messages.

**Comment by amschaal** [comment]
Yeah, I think system wide notifications are what we had in mind.  However, do keep in mind that these messages may not pertain to the majority of Bioshare users.

The error messages are an unrelated issue.

**Comment by msettles** [comment]
Yes error messages are unrelated,the related to everybody issue means we
need to craft the message appropriately. But at the moment, say if you knew
the system would be down on x date there is no way to notify.

Matg

**Comment by amschaal** [comment]
I'm working on a system for this.  I've got a couple questions:
1.  Should users be able to dismiss the notifications once they are seen, or should they stay there until we take them away?
2.  How in your face should they be?  
Really in your face - redirect the user to view the notifications until they dismiss them
Sort of in your face - list each individual notification somewhere prominent
Unobtrusive - Have a small notice saying something like, "There are 3 system notifications" which can be expanded with more details.

**Comment by msettles** [comment]
Probably best to discuss the options when you’re here, I have some idea in my head on what that would look like, but have no idea on how challenging they might be to implement

 

However to answer your questions, they should be in your face, and the user should be able to dismiss once seen


Matt
