### ISSUE TITLE
Characters in folder names

### ISSUE THREAD

**Issue by monicabritton** [amschaal/bioshare#19]
When I try to create a folder within a share, if try I name it, say
October-2016
nothing happens.  No error message or anything.

But if I change it to:
October_2016
or
October 2016

it creates the folder.

Some characters shouldn't be allowed (such as "*", "/"), but I think commonly used ones should (including "-" and even ".").

Or, there should be an error message explaining why the folder create has "failed".  

Thanks!

**Comment by amschaal** [comment]
I'm not allowing "." as a valid character because of its usage in relative directory and URL paths.  I added "-" and "_" as valid characters.  Feel free to suggest others.
