### ISSUE TITLE
Drag Files from Email Attachments

### ISSUE THREAD

**Issue by monicabritton** [amschaal/bioshare#2]
It would be really cool if I could drag a gmail attachment into Bioshare, rather than having to download and upload.  (Tried with Firefox on Linux.)

Thanks!

**Comment by amschaal** [comment]
Unfortunately, that isn't really possible.  That would require the browser telling google to upload the file to Bioshare, using your Bioshare session credentials.  I don't think such a protocol exists, and if it did, you wouldn't want to hand your session credentials to google in order to do it.
