### ISSUE TITLE
Select specific users to receive notification emails

### ISSUE THREAD

**Issue by monicabritton** [amschaal/bioshare#22]
Sometimes there are several people that have been granted permissions to a share, but an email is only intended for a subset of those people.  There should be a way (checkboxes?) to select which addresses each email goes to (but default can be all).

thanks!

**Comment by amschaal** [comment]
Done.  Live on the production site.

**Comment by msettles** [comment]
The “all” could be just a little clearer, so maybe

Checkbox All <list emails comma separated> sometimes its not clear just how many people are on the share unless you first look at permissions.

Matt

**Comment by amschaal** [comment]
Okay, emails are now listed.
