### ISSUE TITLE
When a friendly URL is provided why is it not used by default

### ISSUE THREAD

**Issue by msettles** [amschaal/bioshare#25]
Ex. for this share I have a friendly URL, so why not use it as the default

Greetings,
User settles AT ucdavis.edu has shared 'Wan_Y_UCD_Amplicons' with you on Bioshare. You may access the share at the following URL: https://bioshare.bioinformatics.ucdavis.edu/bioshare/view/6xf4vfidj6r8vqn/

Kind regards, 

The UC Davis Bioinformatics Core

**Comment by msettles** [comment]
Not just emails, but I see the web url is also not the friendly version. So I'd adjust to in all situation when present

**Comment by amschaal** [comment]
Do you see any links to the primary view of the share that don't?  I know there are some views such as the share permissions view, share editing view, etc that don't use the friendly url, but I don't think anyone will be entering the application at those URLs anyhow.

**Comment by msettles** [comment]
So it looks like the only thing left is permissions pages still use the old unidentified
