### ISSUE TITLE
After deletion of share, facilitate return to menu screen

### ISSUE THREAD

**Issue by monicabritton** [amschaal/bioshare#29]
I sorted and filtered my shares just how I wanted them, then went into one of the shares and deleted it.  A message was displayed saying the share was deleted.  But then the only way I could get back to the list of shares was to click on home.  Then I have to sort and filter again!  I would like an easier way to be able to go back to the list.

Alternatively, add a way to delete a share from the list of shares.

Thanks!

**Comment by amschaal** [comment]
Unfortunately, the filters, ordering, and page of the share list are not kept in the browser history.  As a result, the back button will not work.  I would create that as a separate issue.

The short term solution is to open shares in a new tab, and return to the tab that has your filtered/sorted list.
