### ISSUE TITLE
Log of system messages, please

### ISSUE THREAD

**Issue by monicabritton** [amschaal/bioshare#34]
Currently, if the user reads a system message (the ones that appear at the top of the screen), and clicks on "dismiss" it's gone forever.  

There needs to be a log (and a link to that log), so folks can view all the old messages.

(Apologies if this is a duplicate ... I thought I had submitted this issue before but can't find it in open or closed issues.)

Thanks.

**Comment by amschaal** [comment]
For lack of a better place, there is a link to a full list of system messages under Account -> System Messages.
