### ISSUE TITLE
Notify share participants an update has been made

### ISSUE THREAD

**Issue by msettles** [amschaal/bioshare#4]
In a similar manner that participants receive notification they are added to a share, allow for a means to notify the participants that the share has been update, with message. Basically not making it necessary to send an independent email where the users (if after some time) have forgotten where and what to do to access the share

**Comment by amschaal** [comment]
A basic version of this is now implemented.  Anyone who has access to the share can bring up a dialog with prepopulated subject and body fields.  They can edit the fields which include information with the share's name and URL.  The email is sent to everyone with view access for the share, not including superusers.
