### ISSUE TITLE
Write more documentation

### ISSUE THREAD

**Issue by monicabritton** [amschaal/bioshare#5]
For example, specific steps for how to use Cyberduck/Filezilla for SFTP transfers.

Monica

**Comment by amschaal** [comment]
I've been working on documentation in a separate branch.  It is currently hosted at: https://amschaal.github.io/bioshare/
I still have some more to do, and I'd like to improve the structure.  Honestly though, I'm not sure I like github pages as a solution.  I might eventually use the markdown and images to generate a site that lives within the actual Bioshare website.

**Comment by amschaal** [comment]
Improved documentation now available at:
https://bioshare.readthedocs.io/en/latest/

I'll suggest that any requests for documentation be made at the repository that powers it:
https://github.com/amschaal/bioshare-docs
