### ISSUE TITLE
All, outgoing links should open in new tab

### ISSUE THREAD

**Issue by msettles** [amschaal/bioshare#7]
I've accidentally closed bioshare a number of times after clicking on the github link. should open in new tab/window leaving the share as is

**Comment by amschaal** [comment]
Generally, I prefer to leave the choice up to the user.  That way they can choose to open in a new tab or a new window, or sometimes they are okay leaving.  To discuss.

**Comment by msettles** [comment]
Ah, but you are making a choice, your choosing to ‘leave bioshare’, once you click its too late, takes additional action (that the user is likely unaware of) to open a new windes. I’d say for the links on the bottom, github, biocore, gc, not bioshare, etc. it makes sense to open a new tab. Links wholly within bioshare should say say in window

 

My opinino
Matt

**Comment by amschaal** [comment]
Okay, you win.  Outside links are now opened in a new window or tab (depending on their browser settings).
